sudo: required
services:
    - docker
    
before_install:
    - docker build -t andreymaltsev/docker-react01 -f Dockerfile.dev .    
    
script:
    - docker run -e CI=true andreymaltsev/docker-react01 npm run test
    
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react01"
    env: "DockerReact01-env"
    bucket_name: "elasticbeanstalk-us-east-2-481724442910"
    bucket_path: "docker-react01"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
  
